config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

  get 'products' => 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :price_in_cents, presence: true
  validates :price_in_cents, numericality: { only_integer: true }

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

  has_many :reviews

end

app/models/review.rb
class Review < ApplicationRecord
  validates :comment, :product_id, presence: true
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = @product.reviews.build
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product saved!"
      redirect_to "/products"
    else
      render :new
    end
  end

  def edit
     @product = Product.find(params[:id])
  end

  def destroy
    @product = Produt.find(params[:id])
    @product.destroy
    flash[:alert] = "Product Deleted!"
    redirect_to "/products"
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product Updated!"
      redirect_to @product
    else
      redirect_back_or_to @product
    end
  end

private

    def product_params
      params.require(:product).permit(:name, :description, :price_in_cents)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Product.find(params[:product_id]).reviews.new
  end
  # @review = @product.reviews.build

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review saved!"
      redirect_to product_path(@review.product)
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review updated!"
      render 'products/show'
    else
      render 'products/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review destroyed!"
    redirect_to product_path(@review.product)
  end

private

  def review_params
    params.require(:review).permit(:comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
    </header>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'New Product', new_product_path %></li>
      </ul>
    </nav>

    <%= yield %>
  </body>

</html>

app/views/products/_form.html.erb
<%= form_for product do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :price_in_cents %><br>
    <%= f.text_field :price_in_cents %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
    <% product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <h2><%= link_to product.name, product_path(product) %></h2>
  <p><%= product.description %></p>
  <p><%= product.price_in_dollars %></p>
<% end %>

app/views/products/new.html.erb
<%= link_to 'Show all products', products_path %>

<%= render 'form', product: @product %>
<!-- Error messages -->
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@product.errors.count, "error") %> prevented this product from being added</h4>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/products/show.html.erb
<h1><%= link_to @product.name, product_path(@product) %></h1>
  <p><%= @product.description %></p>
  <p><%= @product.price_in_dollars %></p>
  <% @product.reviews.each do |review| %>

    <p><%= review.comment %></p>
    <p><%= review.created_at %></p>
  <% end %>

<%= link_to("Edit", "/products/#{@product.id}/edit") %>
<%= link_to("Delete", "/products/#{@product.id}", method: :delete, data: {confirm: "Do you want to delete this product?"}) %>

<h4>New Review</h4>

<%= render 'reviews/form', product: @product, review: @review %>

app/views/reviews/_form.html.erb
<%= form_for([product, review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h3>Edit Review</h3>

<%= render 'form', product: @product, review: @review %><br>
<%= link_to 'Delete', product_review_path(@product, @review), method: :delete, data: {confirm: "Are you sure you want to delete this review?"} %>